### ISSUE TITLE
Remove this shit Docker and K8s

### ISSUE THREAD

**Issue by rekiiky** [30spb/Alexandria30#5]

**Comment by mikhaillav** [comment]
Это на случай если гитхаб решил что он не вывозит такие нагрузки и отрубит нам Github Pages =)
Сейчас они отключены и не запускаются.

**Comment by ovflw** [comment]
Прям без лоад балансера?

**Comment by ovflw** [comment]
Прям кубер поможет.
Верю

**Comment by mikhaillav** [comment]
На тесте я свой nginx-balancer поставил, не нашел нигде по нормальной цене со встроенным балансером

**Comment by affkie** [comment]
Kubernetes is not needed for the static website deployment

**Comment by ovflw** [comment]
Композ для слабых

**Comment by mikhaillav** [comment]
а разверни-ка мне композом автоматом сайтик с гита и что бы без даунтайма и костылей

**Comment by ovflw** [comment]
Даунтайм это время работы из под к8с со статикой?)

**Comment by ovflw** [comment]
А так это все костыль.

**Comment by ovflw** [comment]
Я такой сайт раскатаю на esp8266. Если не страдать херней это на изи.
https://ru.wikipedia.org/wiki/ESP8266

**Comment by ekeew** [comment]
Lets hear what will blaze egor say about this

**Comment by ovflw** [comment]
А кстати, еще депы я бы зафиксировал по версиям.
Питон и нгинкс в докерфайле, мкдокс в requirements.txt

**Comment by mikhaillav** [comment]
> Даунтайм это время работы из под к8с со статикой?)

наверное да, про даунтайм тут не в тему, но вот про ci/cd я бы послушал

**Comment by mikhaillav** [comment]
> Я такой сайт раскатаю на esp8266. Если не страдать херней это на изи. https://ru.wikipedia.org/wiki/ESP8266

ну это понятно, я чисто хотел разобраться с кубером и сделать все "по красоте"

**Comment by ovflw** [comment]
> > Я такой сайт раскатаю на esp8266. Если не страдать херней это на изи. https://ru.wikipedia.org/wiki/ESP8266
> 
> ну это понятно, я чисто хотел разобраться с кубером и сделать все "по красоте"

Пиши полноценный веб сервис с бд и очередью.

**Comment by mikhaillav** [comment]
> А кстати, еще депы я бы зафиксировал по версиям. Питон и нгинкс в докерфайле, мкдокс в requirements.txt

не совсем понял

**Comment by ovflw** [comment]
> > А кстати, еще депы я бы зафиксировал по версиям. Питон и нгинкс в докерфайле, мкдокс в requirements.txt
> 
> не совсем понял

Версии питона, мкдокс, и нгинкса

**Comment by affkie** [comment]
Specify versions of dependencies

**Comment by mikhaillav** [comment]
а, понял, спасибо

**Comment by ovflw** [comment]
> > Даунтайм это время работы из под к8с со статикой?)
> 
> наверное да, про даунтайм тут не в тему, но вот про ci/cd я бы послушал

С esp8266 даже можно. В меру ущербно изза того что это микроконтроллер а не чтото полноценное.
Jenkins на компе и по usb подключенная esp8266, jenkins шлет обнову по усб в мк. 😁

**Comment by rekiiky** [comment]
Я профессианальный разработчик под есп8663.

**Comment by mikhaillav** [comment]
> > > Даунтайм это время работы из под к8с со статикой?)
> > 
> > 
> > наверное да, про даунтайм тут не в тему, но вот про ci/cd я бы послушал
> 
> С esp8266 даже можно. В меру ущербно изза того что это микроконтроллер а не чтото полноценное. Jenkins на компе и по usb подключенная esp8266, jenkins шлет обнову по усб в мк. 😁

Погуглю на эту тему, спасибо за обратную связь! ❤️

**Comment by mikhaillav** [comment]
> А кстати, еще депы я бы зафиксировал по версиям. Питон и нгинкс в докерфайле, мкдокс в requirements.txt

Исправил в коммите [8aea74a7ceda15ac3f092db74b5d55fc61b53ec3](https://github.com/30spb/Alexandria30/commit/8aea74a7ceda15ac3f092db74b5d55fc61b53ec3). Спасибо!
